version: '3'
services:
  web:
    image: adrianhirt/c9rails:1.2
	networks:
	  - proxy
	container_name: ide
    environment: 
      - user=adrian
      - pass=
	labels:
	  traefik.ide.frontend.rule: "Host:ide.hirt.one;PathPrefixStrip:/"
	  traefik.ide.port: "80"
	  traefik.preview.frontend.rule: "Host:preview.hirt.one;PathPrefixStrip:/"
	  traefik.preview.port: "1337"
	  traefik.enable: "true"
	  traefik.docker.network: "proxy"
networks:
    proxy:
	    external:
		    name: proxy