defaultEntryPoints =["http", "https"]
[web]
address = ":8080"
  [web.auth.basic]
  users = []
[entryPoints]
  [entryPoints.http]
  address = ":80"
	[entryPoints.http.redirect]
	  entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
[acme]
email = ""
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[[acme.domains]]
  main = "ide.hirt.one"
[[acme.domains]]
  main = "preview.hirt.one"
[[acme.domains]]
  main = "monitoring.hirt.one"
[acme.httpChallenge]
  entryPoint = "http"